### ISSUE TITLE
Flicker on scroll

### ISSUE THREAD

**Issue by danriedl** [zMoooooritz/nachrichten#73]
Hey @zMoooooritz , very cool project thanks!!

The UI is flickering while scrolling.
Im using alacritty and zellij.

**Comment by zMoooooritz** [comment]
Hey Dan, thank you for the positive feedback!

I assume this flickering happens while scrolling a news article (not the list of news)?
If this is the case I am unfortunately (I guess) not able to reproduce your described problem while also using alacritty.

Are you on the current release (0.1.7)? If so I would need some additional information in oder to track down the issue :)

**Comment by danriedl** [comment]
Hi Moritz, I did play around with it and it works flawless without zellij. So I guess its not on your side 🥇
